# -*- coding: utf-8 -*-
"""Fast api

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q5FtVCGdnIFywUvmee9_htQ9iiV3FC_l
"""

app = FastAPI()

label_path = '/Users/Downloads/label_mapping.pkl'
with open(label_path, 'rb') as f:
    label_mapping = pickle.load(f)


file_path = '/Users/Downloads/random_forest.pkl'
with open(file_path, 'rb') as model_file:
    loaded_model = pickle.load(model_file)
    print("Model loaded successfully!")


class Item(BaseModel):
    Type: int
    Air_temperature: float

    Process_temperature: float
    Rotational_speed: float
    Torque: float
    Tool_wear: float

@app.post("/predict")
def predict(item: Item):

    new_input = np.array([[item.Type, item.Air_temperature, item.Process_temperature, item.Rotational_speed, item.Torque, item.Tool_wear]])


    predictions = loaded_model.predict(new_input)


    predicted_labels_original = [label_mapping[label] for label in predictions]


    return {"predicted_labels_original": predicted_labels_original}

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host, port=8001)